name: Firmware
on: [push, pull_request, merge_group]

jobs:
  firmware-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target-board:
        - 'cynthion'
        - 'samd11_xplained'
        - 'qtpy'
    steps:
    - name: Install ARM GCC
      uses: carlosperate/arm-none-eabi-gcc-action@v1
      with:
        release: '12.2.Rel1'

    - name: Checkout source code
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Build Apollo firmware for ${{ matrix.target-board }}
      run: |
        cd firmware
        APOLLO_BOARD=${{ matrix.target-board }} make get-deps all
